[package]
name = "converter"
license = "GPL-3.0-or-later"
authors = [
  "Jack Tench",
  "wins1ey <wins1ey at wins1ey dot win>"
]
repository = "https://github.com/LibreSplit/converter"
version = "1.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "staticlib", "rlib"]

[dependencies]
wasm-bindgen = { version = "0.2.128", optional = true }
base64 = "0.23.1"
infer = "0.22.0"
percent-encoding = "2.3.2"
typed-path = "0.12.3"
xml = "1.4.0"

serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
spex = "0.2.2"

[features]
default = []
wasm = ["dep:wasm-bindgen"]

[target.'cfg(target_arch = "wasm32")'.dev-dependencies]
wasm-bindgen-test = "0.3.78"
